### PR TITLE
fret extension

### PR DESCRIPTION
**Pull request by luiztauffer**
NWB extension for storing Fluorescence Resonance Energy Transfer (FRET) experimental data

### CODE REVIEW

**Comment by rly** [comment]
Nice extension @luiztauffer . A couple comments:
1. is the `emission_lambda` attribute on `FRETSeries` necessary? The required `optical_channel` group already has an `emission_lambda`, and in your README example, the `emission_lambda` on `FRETSeries` is 0. It seems like redundant information that could create issues of data integrity.

2. The namespaces.yaml file `author` field should be a list of names instead of "x and y". The `email` field should be a corresponding list of email addresses. i.e., it should look like:
```yaml
namespaces:
- author: 
  - Luiz Tauffer
  - Ben Dichter
  contact: 
  - your email address
  - ben.dichter@gmail.com
```
3. In `requirements.txt`, please use hdmf_docutils instead of nwb_docutils. I will make this change in the template as well.

**Comment by luiztauffer** [comment]
thanks for the comments @rly !
You're right, the emission_lambda is redundant, I will remove it. I will also submit the other changes soon

**Comment by luiztauffer** [comment]
The problems should be fixed now

**Comment by rly** [comment]
Looks great. 

One minor comment about the extension source code -- you can remove `src/spec/export_spec.py`. You are importing it from `pynwb.spec` so you don't need the local copy anymore. 

Since this isn't critical, I'm going to merge the PR which should create a new NDX Catalog record repo for you. You can update the extension record there if desired.

**Pull request merged**
