### PR TITLE
add ndx-miniscope

### PR DESCRIPTION
**Pull request by bendichter**

### CODE REVIEW

**Comment by rly** [comment]
In the catalog entry here:

1. please update your fork to the latest staged-extensions
2. remove .gitignore
3. remove .git extension from git url in ndx-meta.yaml

In the extension itself:

4. please specify the `doc` attribute of the `recordLength` attribute:
`Miniscope.add_attribute(name='recordLength', doc='unknown', dtype='int', required=False)`
5. consider putting `load_miniscope_timestamps` in the pynwb source code, e.g. in `__init__.py` or a new file, since this seems generally useful for all miniscope data
6. it looks like there is more metadata in `settings_and_notes.dat`. why not include them all in the extension?
7. consider writing a custom class instead of using `get_class` where the constructor takes as input a name and the path to the settings_and_notes.dat file and encapsulates the following code, which seems like it would be common to all miniscope data. this would just make it easier for the end user to use the extension.
```python
df = pd.read_csv(settings_and_notes_file, sep='\t').loc[0]
Miniscope(name='Miniscope', excitation=int(df['excitation']),
                      msCamExposure=int(df['msCamExposure']),
                      recordLength=int(df['recordLength']))
```

**Comment by bendichter** [comment]
thanks for the review!

4. I don't actually know what this is. I'll investigate.
6. The settings_and_notes.dat file I was using only had those fields filled out. If I can get ahold of a file that uses the other fields I'd be happy to add them.
7. I'm pretty sure that will break `read` for that class. I can create a convenience function similar to `load_miniscope_timestamps`

The rest look good.

**Comment by rly** [comment]
I found out that record length is the fixed length of the recording, in seconds, that a user can set. Not sure if this is set to be the actual length of the recording if the user leaves it at 0.

There are also the fields `elapsedTime` and `Note` which you can see here:
http://miniscope.org/images/thumb/e/e2/DAQSoftwareDataStructure.png/600px-DAQSoftwareDataStructure.png
http://miniscope.org/images/thumb/f/f5/DAQSoftwareFeatures.png/600px-DAQSoftwareFeatures.png

See sections:
7. To record for a fixed amount of time enter it here. A '0' will run the recording until 'Stop' is clicked.
D. During recording you can submit notes here and they will be saved in the Setting and Notes.dat file along with a timestamp.

**Comment by rly** [comment]
p.s. I had to register for their wiki to access the above. Might be other useful info there. Source code for their DAQ software is here: https://github.com/daharoni/Miniscope_DAQ_Software

**Comment by bendichter** [comment]
OK it looks like `recordLength` can safely omitted since if it is right that info should also be in `timestamps.dat`. `elapsedTime` and `Note` look like a job for `AnnotationSeries`.

**Comment by rly** [comment]
I approve this extension, but before I merge this PR, I need to update/write the automation and CI scripts that run after a PR merge to run tests, create a new repo in the catalog, add maintainers, etc.

**Pull request merged**
